language: node_js
node_js:
  - "4"
  - "6"
  - "8"
cache: yarn
before_script:
  - export DISPLAY=:99.0
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1024x768x16"
  - sleep 3 # give xvfb some time to start
script:
  - npm run lint
  - npm run test
email:
  on_failure: change
  on_success: never

