# https://www.appveyor.com/docs/appveyor-yml/

environment:
  matrix:
    # - node_version: "7"
    - node_version: "6"
    - node_version: "4"
  IE_BIN: "%PROGRAMFILES%\\Internet Explorer\\iexplorer.exe"

cache:
  - "%LOCALAPPDATA%/Yarn"

install:
  - ps: Install-Product node $env:node_version
  - choco install -i yarn
  - refreshenv
  - yarn install

test_script:
  - npm run test-ie

build: off
